/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChillersRouteImport } from './routes/chillers'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ChillersIdRouteImport } from './routes/chillers.$id'

const ChillersRoute = ChillersRouteImport.update({
  id: '/chillers',
  path: '/chillers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ChillersIdRoute = ChillersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ChillersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chillers': typeof ChillersRouteWithChildren
  '/chillers/$id': typeof ChillersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chillers': typeof ChillersRouteWithChildren
  '/chillers/$id': typeof ChillersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chillers': typeof ChillersRouteWithChildren
  '/chillers/$id': typeof ChillersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chillers' | '/chillers/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chillers' | '/chillers/$id'
  id: '__root__' | '/' | '/chillers' | '/chillers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChillersRoute: typeof ChillersRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chillers': {
      id: '/chillers'
      path: '/chillers'
      fullPath: '/chillers'
      preLoaderRoute: typeof ChillersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chillers/$id': {
      id: '/chillers/$id'
      path: '/$id'
      fullPath: '/chillers/$id'
      preLoaderRoute: typeof ChillersIdRouteImport
      parentRoute: typeof ChillersRoute
    }
  }
}

interface ChillersRouteChildren {
  ChillersIdRoute: typeof ChillersIdRoute
}

const ChillersRouteChildren: ChillersRouteChildren = {
  ChillersIdRoute: ChillersIdRoute,
}

const ChillersRouteWithChildren = ChillersRoute._addFileChildren(
  ChillersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChillersRoute: ChillersRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
