/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ChillersRouteImport } from './routes/chillers'
import { Route as IndexRouteImport } from './routes/index'

const ChillersRoute = ChillersRouteImport.update({
  id: '/chillers',
  path: '/chillers',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chillers': typeof ChillersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chillers': typeof ChillersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chillers': typeof ChillersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/chillers'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/chillers'
  id: '__root__' | '/' | '/chillers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChillersRoute: typeof ChillersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/chillers': {
      id: '/chillers'
      path: '/chillers'
      fullPath: '/chillers'
      preLoaderRoute: typeof ChillersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChillersRoute: ChillersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
